version: "3.8"

# ==============================================================================
# ANCHORS
# ==============================================================================

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "500k"
    max-file: "20"

x-entrypoint: &default-entrypoint
  entrypoint: >
    /bin/sh -c "
      set -e
      echo Waiting TTY interation..
      /bin/bash || exit 0
    "

# ==============================================================================
# SERVICES
# ==============================================================================

services:

  web:
    container_name: web
    build:
      context: $PATH_DOCKERFILE
      dockerfile: Dockerfile
    env_file: [ "./.env" ]
    <<: *default-entrypoint
    stdin_open: true
    tty: true
    restart: on-failure
    logging: *default-logging
    networks: [ "web" ]

  postgres:
    image: postgres:9.6
    container_name: postgres
    env_file: [ "./.env" ]
    ports: [ 5432:5432 ]
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

# ==============================================================================
# NETWORKS
# ==============================================================================

networks:
  web:
